### ISSUE TITLE
Not working on ubuntu 20.04 with python 3.10

### ISSUE THREAD

**Issue by laoshaw** [aws-samples/amazon-live-translation-polly-transcribe#1]
After I selected the audio device and translation(1 or 2):

```
Choose device [{'index': 26, 'structVersion': 2, 'name': 'default', 'hostApi': 0, 'maxInputChannels': 32, 'maxOutputChannels': 32, 'defaultLowInputLatency': 0.008707482993197279, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultHighInputLatency': 0.034829931972789115, 'defaultHighOutputLatency': 0.034829931972789115, 'defaultSampleRate': 44100.0}]: 26

Selection is input using standard mode.

Choose source and target language to translate. 1 for en to zh, 2 for zh to en [1]: 
Traceback (most recent call last):
  File "/home/aws01/amazon-live-translation-polly-transcribe/language_assistant.py", line 247, in <module>
    direction = int(input("Choose source and target language to translate. 1 for en to zh, 2 for zh to en [" + textcolors.blue + str(direction) + textcolors.end + "]: ") or default_device_index)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'dict'
```

**Comment by laoshaw** [comment]
so I 'fixed' above error but I got another one:

```
Choose device [{'index': 26, 'structVersion': 2, 'name': 'default', 'hostApi': 0, 'maxInputChannels': 32, 'maxOutputChannels': 32, 'defaultLowInputLatency': 0.008707482993197279, 'defaultLowOutputLatency': 0.008707482993197279, 'defaultHighInputLatency': 0.034829931972789115, 'defaultHighOutputLatency': 0.034829931972789115, 'defaultSampleRate': 44100.0}]: 21

Selection is input using standard mode.

Choose source and target language to translate. 1 for en to zh, 2 for zh to en [1]: 1
/home/aws01/amazon-live-translation-polly-transcribe/language_assistant.py:325: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
getting mic stream
{'index': 21, 'structVersion': 2, 'name': 'speexrate', 'hostApi': 0, 'maxInputChannels': 128, 'maxOutputChannels': 128, 'defaultLowInputLatency': 0.007755102040816327, 'defaultLowOutputLatency': 0.007755102040816327, 'defaultHighInputLatency': 0.023219954648526078, 'defaultHighOutputLatency': 0.023219954648526078, 'defaultSampleRate': 44100.0}
started stream
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Traceback (most recent call last):
  File "/home/aws01/amazon-live-translation-polly-transcribe/language_assistant.py", line 326, in <module>
    loop.run_until_complete(transcribe())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
SystemError
```

**Comment by laoshaw** [comment]
pyaudio is broken for python 3.10, I had to build it from source
